### PR TITLE
allow configurable master alias

### LINKED ISSUE #127: Master CF stack name convention
By the default, when we deploy the first version without alias option, the plugin creates a master CF stack name with suffix is (dev) i.e. sls-test-project-dev, also APIG is creating with dev prefix i.e. dev-sls-test-project. Is that possible to not adding suffix/prefix to APIG and Master CF stacks?

image

image

In fact, we only want to just create a master CF for the serverless with the name that we named in the serverless.yml (e.g. sls-test-project), also APIG name should the same. Adding prefix to APIG will make us confused that we will have more APIGs to be created for the same project which will never happen when using this plugin.

### PR DESCRIPTION
**Pull request by aleksdikanski**
This fixes #127 and will allow the master alias name to be selected by a command line option `sls deploy --masterAlias <masterAlias>`. The master alias name will be exported in the base stack as value and will be used upon removal of the stack.

### CODE REVIEW

**Comment by Enase** [comment]
Could you update `README.md`?

**Comment by HyperBrain** [comment]
It looks like this first has to be rebased onto the current master. There are a lot more differences than just the "allow master alias ..." ;-)

**Comment by HyperBrain** [comment]
It looks like there are files with conflict markers committed in there. Can you have a look?

**Comment by aleksdikanski** [comment]
@HyperBrain Sorry for the rebase mess :) Should all be fixed now.

**Pull request merged**
