### PR TITLE
Supporting dash in alias name when creating api gateway authorizers

### PR DESCRIPTION
**Pull request by ziadloo**
Replacing the `-` in the alias for the API Gateway template name. Without this change, chosing an alias name with `-` in it while your definition has an API Gateway with authorizers in it will fail.

### CODE REVIEW

**Comment by ziadloo** [comment]
@HyperBrain I appreciate it if you could take a look at this. It's been sitting here for a month and a half. I need this published. Thanks.

**Comment by aniva** [comment]
Hi, thanks for approving it, when it will be published to npm?

**Comment by Enase** [comment]
coming soon.. today, I hope..

**Comment by aniva** [comment]
Thanks a lot and have a great day!

**Pull request merged**
